export default  [
    {
        id:1,
        name: 'Best of Paris in 7 Days Tour',
        price:'$1995',
        img:'https://www.course-api.com/images/tours/tour-1.jpeg',
        info:'Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour, your Paris-savvy Rick Steves guide will immerse you in the very best of the City of Light: the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. Youll also enjoy guided neighborhood walks through the cityhistoric heart as well as quieter moments to slow down and savor the citys intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!',
    },
        {    id:2,
        name: <h3>Best of Paris in 7 Days Tour</h3>,
        price:'$1995',
        img:'https://www.course-api.com/images/tours/tour-2.jpeg',
        info:'Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour, your Paris-savvy Rick Steves guide will immerse you in the very best of the City of Light: the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. Youll also enjoy guided neighborhood walks through the cityhistoric heart as well as quieter moments to slow down and savor the citys intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!',
    },
            {    id:3,
        name: <h3>Best of Paris in 7 Days Tour</h3>,
        price:'$1995',
        img:'https://www.course-api.com/images/tours/tour-3.jpeg',
        info:'Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour, your Paris-savvy Rick Steves guide will immerse you in the very best of the City of Light: the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. Youll also enjoy guided neighborhood walks through the cityhistoric heart as well as quieter moments to slow down and savor the citys intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!',
    },
                {    id:4,
        name: <h3>Best of Paris in 7 Days Tour</h3>,
        price:'$1995',
        img:'https://www.course-api.com/images/tours/tour-4.jpeg',
        info:'Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour, your Paris-savvy Rick Steves guide will immerse you in the very best of the City of Light: the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. Youll also enjoy guided neighborhood walks through the cityhistoric heart as well as quieter moments to slow down and savor the citys intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!',
    },
                    {    id:5,
        name: <h3>Best of Paris in 7 Days Tour</h3>,
        price:'$1995',
        img:'https://www.course-api.com/images/tours/tour-5.jpeg',
        info:'Paris is synonymous with the finest things that culture can offer — in art, fashion, food, literature, and ideas. On this tour, your Paris-savvy Rick Steves guide will immerse you in the very best of the City of Light: the masterpiece-packed Louvre and Orsay museums, resilient Notre-Dame Cathedral, exquisite Sainte-Chapelle, and extravagant Palace of Versailles. Youll also enjoy guided neighborhood walks through the cityhistoric heart as well as quieter moments to slow down and savor the citys intimate cafés, colorful markets, and joie de vivre. Join us for the Best of Paris in 7 Days!',
    }
]